WITH DAILY_WEATHER AS (
    SELECT 
    DATE(TIME) AS DAILY_WEATHER,
    WEATHER,
    TEMP,
    PRESSURE,
    HUMIDITY,
    CLOUDS

    FROM {{source('demo','weather')}}
),

DAILY_WEATHER_AGG AS (
    SELECT
    DAILY_WEATHER,
    WEATHER,
    ROUND(AVG(TEMP),2) AS AVG_TEMP,
    ROUND(AVG(PRESSURE),2)AS AVG_PRESSURE,
    ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
    ROUND(AVG(CLOUDS),2) AS AVG_CLOUDS

    FROM DAILY_WEATHER

    GROUP BY DAILY_WEATHER, WEATHER

    QUALIFY ROW_NUMBER() OVER (PARTITION BY DAILY_WEATHER ORDER BY COUNT(WEATHER) DESC) = 1
)

SELECT * FROM DAILY_WEATHER_AGG